/**
 * Shared zod schemas and validation helpers for API route input validation.
 *
 * All AI-touching and Snowflake-touching routes should validate their inputs
 * here before reaching business logic.
 */
import { z } from 'zod';
import { NextResponse } from 'next/server';

// ── Primitive schemas ─────────────────────────────────────────────────────────

/**
 * UUID v4 — used for app-generated IDs (NOTE_ID, TASK_ID) created via
 * Node crypto.randomUUID().
 */
export const UuidSchema = z.string().uuid('Invalid ID format');

/**
 * Physician IDs come from Snowflake as short codes (e.g. "PHY005"), not UUIDs.
 * Accept any non-empty string.
 */
export const PhysicianIdSchema = z.string().min(1, 'physicianId is required');

/** Transcripts are capped to prevent runaway AI token costs. */
const MAX_TRANSCRIPT_CHARS = 100_000;
export const TranscriptSchema = z
  .string()
  .min(1, 'transcript is required')
  .max(MAX_TRANSCRIPT_CHARS, `transcript must be under ${MAX_TRANSCRIPT_CHARS} characters`);

// ── Per-endpoint input schemas ─────────────────────────────────────────────

export const PlaybookInputSchema = z.object({
  physicianId: PhysicianIdSchema,
});

export const EvalSubmitInputSchema = z.object({
  physicianId: PhysicianIdSchema,
  transcript: TranscriptSchema,
});

export const SummarizeInputSchema = z.object({
  transcript: TranscriptSchema,
});

export const ExtractInputSchema = z.object({
  noteId: UuidSchema,          // generated by crypto.randomUUID() — is a real UUID
  physicianId: PhysicianIdSchema,
  transcript: TranscriptSchema,
});

export const CreateTaskInputSchema = z.object({
  physicianId: PhysicianIdSchema,
  taskText: z.string().min(1, 'taskText is required').max(500, 'taskText must be under 500 characters'),
});

export const UpdateTaskInputSchema = z.object({
  taskId: UuidSchema,
  completed: z.boolean().optional(),
  deleted: z.boolean().optional(),
});

// ── Helper ────────────────────────────────────────────────────────────────────

/**
 * Parse and validate `body` against `schema`.
 * Returns `{ data }` on success or `{ errorResponse }` on failure.
 */
export function validateInput<T>(
  schema: z.ZodSchema<T>,
  body: unknown,
): { data: T; errorResponse?: never } | { data?: never; errorResponse: NextResponse } {
  const result = schema.safeParse(body);
  if (!result.success) {
    const message = (result.error.issues ?? (result.error as any).errors ?? []).map((e: any) => e.message).join('; ');
    return {
      errorResponse: NextResponse.json({ error: message }, { status: 400 }),
    };
  }
  return { data: result.data };
}
